name: Generate terraform docs
on:
    push:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Render terraform docs and commit changes back
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "chore: update TF_DOCS"